affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i4
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  ZAAAAA==
grid_eps: 1.0
grid_range:
- -1
- 1
k: 3
mult_arity: 2
sb_trainable: true
sp_trainable: true
state_id: 1
symbolic.funs_name.0:
- - '0'
  - '0'
symbolic.funs_name.1:
- - '0'
symbolic_enabled: true
width:
- - 2
  - 0
- - 1
  - 0
- - 1
  - 0
